import java.util.*;
class exception
{
	public static void main(String args[])
	{
		try
		{
			int[] num={1,2,3};
		}
		catch (Exception e)
		{
			System.out.println("error occured in program");
		}
		finally 
		{
			System.out.println("Try ans Catch excecuted successfully");
		}
	}
}
